name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    steps:
    - name: Test inside docker
      run: docker run --rm vieraleonel1/tnt2021:untdf-01-03-test-falla npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "untdf-actividad-03" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
